HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
X-Powered-By: PHP/{phpVersion}
Content-Length: 103

array (
  'foo_' => 'bar',
  '_dot_' => 'val  ',
  'PHPSESSID' => '1234',
  'secondCookie' => 'test',
)