HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
X-Powered-By: PHP/{phpVersion}
Content-Length: 326

hello<br />
<b>Fatal error</b>:  Uncaught Exception: request 0 in {documentRoot}/exception.php:7
Stack trace:
#0 {documentRoot}/_executor.php(5): {closure:{documentRoot}/exception.php:5}()
#1 {documentRoot}/exception.php(3): require_once('{documentRoot}/_ex...')
#2 {main}
  thrown in <b>{documentRoot}/exception.php</b> on line <b>7</b><br />
